// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_API_KEY_FOR_WEB']}',
    appId: '1:518466479592:web:faea4933a48f2aa485305d',
    messagingSenderId: '518466479592',
    projectId: 'nafas-app',
    authDomain: 'nafas-app.firebaseapp.com',
    storageBucket: 'nafas-app.firebasestorage.app',
    measurementId: 'G-J5X60ENJVW',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_API_KEY_FOR_ANDROID']}',
    appId: '1:518466479592:android:7aea91a055f1cebf85305d',
    messagingSenderId: '518466479592',
    projectId: 'nafas-app',
    storageBucket: 'nafas-app.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_API_KEY_FOR_IOS']}',
    appId: '1:518466479592:ios:0c71c8fd9d8eabc385305d',
    messagingSenderId: '518466479592',
    projectId: 'nafas-app',
    storageBucket: 'nafas-app.firebasestorage.app',
    iosClientId: '518466479592-rtrm495falocbl758un4hosj36tiep5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.nafasApp',
  );
}
